services:
  server:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./app/:/app/
    command: uvicorn app.main:app --reload --workers 1 --host 0.0.0.0 --port 8000
    ports:
     - 8000:8000